Repository pixeldothorse/pixel.horse, pull requests merged in 2019-09, with the labels that each got.

#67 Rebrand fully
  assets/images/logo-120.png
  assets/images/logo-64.png
  assets/images/logo-gray.png
  assets/images/logo-large.png
  assets/images/logo-small.png
  assets/images/logo.png
  favicons/android-chrome-192x192.png
  favicons/android-chrome-512x512.png
  favicons/apple-touch-icon-152x152.png
  favicons/apple-touch-icon-precomposed.png
  favicons/apple-touch-icon.png
  favicons/browserconfig.xml
  favicons/favicon-16x16.png
  favicons/favicon-194x194.png
  favicons/favicon-32x32.png
  favicons/favicon.ico
  favicons/manifest.json
  favicons/mstile-150x150.png
  favicons/safari-pinned-tab.svg
  public/offline.html
  public/privacypolicy.html
  public/reload.html
  public/reset.html
  public/termsofservice.html
Labels: rewrite

#78 Remove word filtering of expressions via command
  src/ts/common/expressionUtils.ts
  src/ts/server/chat.ts
  src/ts/server/commands.ts
Labels: gameplay

#83 Perform sprite compilation before rev'ing and copying
  gulpfile.js
Labels: bug, tooling

#80 Security: Don't allow default secret/token config parameters
  README.md
  config-template.json
  src/ts/server/config.ts
Labels: bug

#98 Use season in entity draw options for map renderer tool
  src/ts/components/tools/tools-map/tools-map.ts
Labels: feature, rewrite, tooling

#100 Attempt to fix build, part 3
  README.md
  gulpfile.js
  package.json
Labels: rewrite, tooling

#85 Add chat log colors, timestamp, filter & emoji box
  src/ts/common/color.ts
  src/ts/common/interfaces.ts
  src/ts/components/shared/chat-box/chat-box.pug
  src/ts/components/shared/chat-box/chat-box.scss
  src/ts/components/shared/chat-box/chat-box.ts
  src/ts/components/shared/chat-log/chat-log.pug
  src/ts/components/shared/chat-log/chat-log.scss
  src/ts/components/shared/chat-log/chat-log.ts
  src/ts/components/shared/settings-modal/settings-modal.pug
  src/ts/components/shared/settings-modal/settings-modal.ts
Labels: feature

#124 Actions: use Node 10.x
  .github/workflows/push.yml
Labels: meta

#128 Add shrug command
  src/ts/components/shared/chat-box/chat-box.ts
  src/ts/server/commands.ts
Labels: gameplay

#126 Clarify initial sprites build, repo quirks
  README.md
Labels: documentation

#137 Archive update v0.54.0
  LICENSE_ART.txt
  README.md
  assets/images/logo-pt-small.png
  package.json
  src/ts/client/credits.ts
  src/ts/client/draw.ts
  src/ts/client/game.ts
  src/ts/client/webgl.ts
  src/ts/common/interfaces.ts
  src/ts/common/pony.ts
  src/ts/components/shared/action-bar/action-bar.pug
  src/ts/components/shared/action-bar/action-bar.ts
  src/ts/components/shared/actions-modal/actions-modal.ts
  src/ts/components/shared/visit-pt-button/visit-pt-button.pug
  src/ts/graphics/contextSpriteBatch.ts
  src/ts/graphics/paletteSpriteBatch.ts
  src/ts/graphics/shaders/palette-layers.glsl
  src/ts/graphics/webgl/frameBuffer.ts
Labels: upstream

#140 Append trailing / to config.host if not present
  src/ts/server/config.ts
Labels: bug, rewrite

#138 Season and holiday configuration options
  README.md
  config-template.json
  src/ts/common/adminInterfaces.ts
  src/ts/common/constants.ts
  src/ts/common/utils.ts
  src/ts/server/commands.ts
  src/ts/server/config.ts
  src/ts/server/serverActionsManager.ts
Labels: rewrite
